// let a=prompt().trim();
// console.log(a);
// let a="              Illovegullu            ";
// // let x=a.toUpperCase().trim().slice(0).replace("LOVE","verymuchlove");
// // let x=a.replace("love","cute");
// let x=a.repeat(3);
// console.log(x);
// let x="Apnacollage";
// let a=x.slice(4).replace("ll","tt")
// console.log(a);
// let x=[1,'a',3.1];
// console.log(x);
// let y=x.length;
// console.log(y);
// let n=["a",'b','v'];
// n.push('r');
// console.log(n);
// n.pop();
// console.log(n);
// n.shift();
// console.log(n);
// let b=['j','f','m','a'];

// // b.shift();
// // b.shift();
// // b.unshift("apr");
// // b.unshift("jul");
// console.log(b);
// let f=b.indexOf('f');
// console.log(f);
// let m=b.includes('n');
// console.log(m);
let x=['a',2.1,'c',1,2,3];
// let y=[1,2,3];
// let m=x.concat(y);
// console.log(m);
// let p=x.reverse();
// console.log(p);
//  let l=x.slice();
// console.log(c);
// let a=x.slice(1);
// console.log(a);
// let b=x.slice(1,2);
// console.log(b);
// let c=x.slice(-2);
// console.log(c);

let month =['jan','fe','ma','ap'];
let f=month.splice(0,2,'dec','nov');
console.log(month);